workflows:
  ditonton-workflow:
    name: Ditonton
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.5
    publishing:
      email:
        recipients:
          - aaronevanjulio18@gmail.com
        notify:
          success: true
          failure: true